# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_author_author_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_fk',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.ForeignKey(help_text='Enter name of blog author', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
