# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 12:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_auto_20170118_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_fk',
            field=models.ForeignKey(help_text='Enter name of blog author', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(default='', help_text='Enter name of blog author', max_length=200),
            preserve_default=False,
        ),
    ]
